### ISSUE TITLE
Mainnet?

### ISSUE THREAD

**Issue by theeldermillenial** [fallen-icarus/cardano-swaps#13]
Hey all,

Has this protocol been released on mainnet yet? I see the example all use test net.

Love what you guys are developing.

**Comment by fallen-icarus** [comment]
> Has this protocol been released on mainnet yet?

It already works on mainnet, but it isn't recommended yet. If people are willing to accept the risks, just replace `--testnet` with `--mainnet` everywhere in the examples. I'd like to wait until after optimizations are added and audits are done before officially recommending it for mainnet.

**Comment by theeldermillenial** [comment]
Thanks for the quick reply. Do you have a timetable for that? I would be interested in making a Python client to interact with it. I'm not super picky about ownership, so I could either host the repo for it here or include into this repo. I currently have all the DEX AMM swap mechanisms implemented in Python, and I'm interested in expanding that to cover all "swap" mechanisms on Cardano.

I like how decentralized you have made this, and the swap mechanism seems very elegant. I can only imagine the possibilities of transaction composability with this. I think GY is using a similar mechanism, although I think yours is definitely more decentralized-focused (which I prefer).

**Comment by fallen-icarus** [comment]
> Do you have a timetable for that?

Unfortunately, no I don't. My goal is to be done with rcv2 by February; it has some significant optimizations. This is the earliest point I would consider getting audits. If community members come up with other optimizations/features, this timeline may be pushed back; I'd rather have it as stable as possible before an official launch.

> I would be interested in making a Python client to interact with it. I'm not super picky about ownership, so I could either host the repo for it here or include into this repo.

If you are not too discouraged by the ambiguous timeline, I would actually appreciate you doing this even though it is still in beta. Currently, the only way to demo it is with the CLI I created and the only client is in haskell. If there was another method, more people may be able to try it out (and possibly create their own frontends for it). I'm fine with you hosting the repo for it. If you do create it, we can announce it on twitter once you're done.

**Comment by theeldermillenial** [comment]
I will take that as an implicit green light :)

I understand how these things go with ambiguous timelines.

I'll try to set up the code in such a way to prepare for future changes.

**Comment by fallen-icarus** [comment]
I'm going to close this issue since it was just a question but feel free to message here if you have any questions/comments while creating the python client. You can also use this thread to let me know when you are done.

**Comment by theeldermillenial** [comment]
@fallen-icarus Is there a better place for me to contact you? Discord?

**Comment by fallen-icarus** [comment]
@theeldermillenial Yeah, my discord username is `fallen.icarus.` (including the trailing period).
