### ISSUE TITLE
v3.0.0 aiken build failed

### ISSUE THREAD

**Issue by madchickenisreal** [fallen-icarus/cardano-swaps#7]
I got bellow error after run `aiken build --keep-traces`
aiken version: aiken v1.0.8-alpha c5af6e0
![Screenshot 2023-07-25 at 17 45 50](https://github.com/fallen-icarus/cardano-swaps/assets/119288229/dbcd3ac9-3541-49fe-a714-ee861ca91421)

**Comment by fallen-icarus** [comment]
It is using the wrong version of the aiken standard library. I assumed the version of aiken was tied to the version of the aiken stdlib but this turns out to be false. In the file `aiken/aiken.toml`, the stdlib version must be changed from "main" to "1.0.0".

**Comment by madchickenisreal** [comment]
the problem resolved. thanks a lot,
